### ISSUE TITLE
raygun.rb syntax error, unexpected tLABEL

### ISSUE THREAD

**Issue by liub3** [MindscapeHQ/raygun4ruby#118]
Follow the instruction I installed gem successfully, however when I run  "`rails g raygun:install <API_KEY>`", ruby generate syntax errors from raygun.rb (will show errors below). Here is my development environment: `ruby 1.9.3-p551, rails 3.1.12, raygun4ruby 2.1.0`
The syntax error makes server not able to start absolutely.
Error messages:
```
/Users/auser/.rvm/gems/ruby-1.9.3-p551/gems/activesupport-3.1.12/lib/active_support/dependencies.rb:240:in `require': /Users/auser/.rvm/gems/ruby-1.9.3-p551/gems/raygun4ruby-2.1.0/lib/raygun.rb:86: syntax error, unexpected tLABEL, expecting ')' (SyntaxError)
        message: nil,
                ^
/Users/auser/.rvm/gems/ruby-1.9.3-p551/gems/raygun4ruby-2.1.0/lib/raygun.rb:86: Can't assign to nil
/Users/auser/.rvm/gems/ruby-1.9.3-p551/gems/raygun4ruby-2.1.0/lib/raygun.rb:90: syntax error, unexpected tLABEL, expecting '='
        metadata: {},
                 ^
/Users/auser/.rvm/gems/ruby-1.9.3-p551/gems/raygun4ruby-2.1.0/lib/raygun.rb:91: Can't assign to nil
/Users/auser/.rvm/gems/ruby-1.9.3-p551/gems/raygun4ruby-2.1.0/lib/raygun.rb:92: Can't assign to nil
/Users/auser/.rvm/gems/ruby-1.9.3-p551/gems/raygun4ruby-2.1.0/lib/raygun.rb:149: syntax error, unexpected keyword_end, expecting $end
	from /Users/auser/.rvm/gems/ruby-1.9.3-p551/gems/activesupport-3.1.12/lib/active_support/dependencies.rb:240:in `block in require'
	from /Users/auser/.rvm/gems/ruby-1.9.3-p551/gems/activesupport-3.1.12/lib/active_support/dependencies.rb:223:in `block in load_dependency'
	from /Users/auser/.rvm/gems/ruby-1.9.3-p551/gems/activesupport-3.1.12/lib/active_support/dependencies.rb:640:in `new_constants_in'
	from /Users/auser/.rvm/gems/ruby-1.9.3-p551/gems/activesupport-3.1.12/lib/active_support/dependencies.rb:223:in `load_dependency'
	from /Users/auser/.rvm/gems/ruby-1.9.3-p551/gems/activesupport-3.1.12/lib/active_support/dependencies.rb:240:in `require'
	from /Users/auser/.rvm/gems/ruby-1.9.3-p551/gems/raygun4ruby-2.1.0/lib/raygun4ruby.rb:1:in `<top (required)>'
	from /Users/auser/.rvm/gems/ruby-1.9.3-p551/gems/bundler-1.11.2/lib/bundler/runtime.rb:77:in `require'
	from /Users/auser/.rvm/gems/ruby-1.9.3-p551/gems/bundler-1.11.2/lib/bundler/runtime.rb:77:in `block (2 levels) in require'
	from /Users/auser/.rvm/gems/ruby-1.9.3-p551/gems/bundler-1.11.2/lib/bundler/runtime.rb:72:in `each'
	from /Users/auser/.rvm/gems/ruby-1.9.3-p551/gems/bundler-1.11.2/lib/bundler/runtime.rb:72:in `block in require'
	from /Users/auser/.rvm/gems/ruby-1.9.3-p551/gems/bundler-1.11.2/lib/bundler/runtime.rb:61:in `each'
	from /Users/auser/.rvm/gems/ruby-1.9.3-p551/gems/bundler-1.11.2/lib/bundler/runtime.rb:61:in `require'
	from /Users/auser/.rvm/gems/ruby-1.9.3-p551/gems/bundler-1.11.2/lib/bundler.rb:99:in `require'
	from /Users/auser/repo/api/config/application.rb:7:in `<top (required)>'
	from /Users/auser/.rvm/gems/ruby-1.9.3-p551/gems/railties-3.1.12/lib/rails/commands.rb:21:in `require'
	from /Users/auser/.rvm/gems/ruby-1.9.3-p551/gems/railties-3.1.12/lib/rails/commands.rb:21:in `<top (required)>'
	from script/rails:6:in `require'
	from script/rails:6:in `<main>'
```

**Comment by liub3** [comment]
OK, I bundled slightly old versions `raygun4ruby (1.5.0 and 2.0.0)` and those syntax errors are gone. I think just the latest version has those syntax problems.

**Comment by UberMouse** [comment]
Hi liub3,

We dropped support for Ruby 1.9.3 in the 2.0 update but 2.1 was the first release with changes that would not work on 1.9.3. I realize that I have forgotten to update the version requirement in the readme however. 

The Ruby 1.9.3 incompatible syntax is what is causing your issue with 2.1.0.

**Comment by liub3** [comment]
Thank you for your reply I think you also need to update "REQUIRED RUBY VERSION:" on this page [](https://rubygems.org/gems/raygun4ruby/versions/2.1.0)

**Comment by UberMouse** [comment]
Thanks for that :) good catch. I see we've never filled that out. I've updated it to >= 2 but that won't get applied until the next release unfortunately as I don't believe there is a way to update existing releases.

**Comment by gonace** [comment]
A year later and it still says "Required Ruby Version: >= 0", should be changed to prevent frustration for users running old versions of ruby, even though 1.9.3 is kind of old.

**Comment by UberMouse** [comment]
Sorry, I don't have a clue what I did when I said I updated it to >= 2 but clearly it didn't work and I never checked. I'll fix it when I get to work on Monday.
