### ISSUE TITLE
Logs littered with undefined method `pos' for #<Unicorn::TeeInput:0x000000158d8398>

### ISSUE THREAD

**Issue by TSMMark** [MindscapeHQ/raygun4ruby#122]
Every some seconds.

https://github.com/MindscapeHQ/raygun4ruby/blob/master/lib/raygun/client.rb#L144

```
F, [2017-08-28T06:46:33.634868 #2092] FATAL -- : Exception Class: NoMethodError
Exception message: undefined method `pos' for #<Unicorn::TeeInput:0x000000158d8398>

===================================================================
Backtrace:
===================================================================

  /home/deploy/apps/vydia/shared/bundle/ruby/2.1.0/gems/raygun4ruby-2.3.0/lib/raygun/client.rb:144:in `raw_data'
  /home/deploy/apps/vydia/shared/bundle/ruby/2.1.0/gems/raygun4ruby-2.3.0/lib/raygun/client.rb:102:in `request_information'
  /home/deploy/apps/vydia/shared/bundle/ruby/2.1.0/gems/raygun4ruby-2.3.0/lib/raygun/client.rb:194:in `build_payload_hash'
  /home/deploy/apps/vydia/shared/bundle/ruby/2.1.0/gems/raygun4ruby-2.3.0/lib/raygun/client.rb:26:in `track_exception'
  /home/deploy/apps/vydia/shared/bundle/ruby/2.1.0/gems/raygun4ruby-2.3.0/lib/raygun.rb:123:in `track_exception_sync'
  /home/deploy/apps/vydia/shared/bundle/ruby/2.1.0/gems/raygun4ruby-2.3.0/lib/raygun.rb:61:in `track_exception'
  /home/deploy/apps/vydia/shared/bundle/ruby/2.1.0/gems/raygun4ruby-2.3.0/lib/raygun.rb:137:in `rescue in track_exception_sync'
  /home/deploy/apps/vydia/shared/bundle/ruby/2.1.0/gems/raygun4ruby-2.3.0/lib/raygun.rb:121:in `track_exception_sync'
  /home/deploy/apps/vydia/shared/bundle/ruby/2.1.0/gems/raygun4ruby-2.3.0/lib/raygun.rb:61:in `track_exception'
  /home/deploy/apps/vydia/shared/bundle/ruby/2.1.0/gems/raygun4ruby-2.3.0/lib/raygun/middleware/rack_exception_interceptor.rb:12:in `rescue in call'
  /home/deploy/apps/vydia/shared/bundle/ruby/2.1.0/gems/raygun4ruby-2.3.0/lib/raygun/middleware/rack_exception_interceptor.rb:10:in `call'
```

**Comment by TSMMark** [comment]
Sure enough TeeInput does not have a `pos` instance method: https://bogomips.org/unicorn/Unicorn/TeeInput.html
