### ISSUE TITLE
How to disable javascript?

### ISSUE THREAD

**Issue by Paxa** [MindscapeHQ/raygun4ruby#139]
After upgrading to new version I got error in my tests. How to disable it?

```
NoMethodError: undefined method `[]' for #<ActionDispatch::Response::RackBody:0x00007f9181c888f8>
    /Users/pavel/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/gems/rack-2.0.6/lib/rack/body_proxy.rb:41:in `method_missing'
    /Users/pavel/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/gems/raygun4ruby-3.1.0/lib/raygun/middleware/javascript_exception_tracking.rb:19:in `inject_javascript_to_response'
    /Users/pavel/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/gems/raygun4ruby-3.1.0/lib/raygun/middleware/javascript_exception_tracking.rb:12:in `call'
    /Users/pavel/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/gems/actionpack-5.2.2/lib/action_dispatch/middleware/debug_exceptions.rb:61:in `call'
    /Users/pavel/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/gems/actionpack-5.2.2/lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
    /Users/pavel/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/gems/railties-5.2.2/lib/rails/rack/logger.rb:38:in `call_app'
 ```

And I don't want any javascript injected in my app automatically

**Comment by Paxa** [comment]
Solved by:

```ruby
# initializers/raygun.rb
if defined?(Raygun::Middleware::JavascriptExceptionTracking)
  Rails.configuration.middleware.delete Raygun::Middleware::JavascriptExceptionTracking
end
```

**Comment by Paxa** [comment]
> it only injects the Javascript snippet to load Raygun4JS if you have specified an API key to use for Javascript error tracking in your configuration.
Sorry my misunderstanding from reading changelog

**Comment by Paxa** [comment]
Thank you
