### ISSUE TITLE
raygun4ruby crashing server with Graphql requests

### ISSUE THREAD

**Issue by fatfrog** [MindscapeHQ/raygun4ruby#162]
Full Backtrace
NoMethodError: undefined method `match' for nil:NilClass
middleware.rb  21 instrument(...)

```
def instrument(env)
  # Ignore asset requests
  if env['REQUEST_PATH'].match(/^\/assets\//)
      return @app.call(env)
  end
```

```
raygun-apm-rails (1.0.57) lib/raygun/apm/rails/middleware.rb:21:in `instrument'
[0d3df8f7-9a61-4c2e-aa0e-d7a5be4fd22f] raygun-apm-rails (1.0.57) lib/raygun/apm/rails/middleware.rb:13:in `call'
[0d3df8f7-9a61-4c2e-aa0e-d7a5be4fd22f] newrelic_rpm (6.10.0.364) lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
[0d3df8f7-9a61-4c2e-aa0e-d7a5be4fd22f] newrelic_rpm (6.10.0.364) lib/new_relic/rack/agent_hooks.rb:30:in `traced_call'
[0d3df8f7-9a61-4c2e-aa0e-d7a5be4fd22f] newrelic_rpm (6.10.0.364) lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
[0d3df8f7-9a61-4c2e-aa0e-d7a5be4fd22f] newrelic_rpm (6.10.0.364) lib/new_relic/rack/browser_monitoring.rb:33:in `traced_call'
[0d3df8f7-9a61-4c2e-aa0e-d7a5be4fd22f] newrelic_rpm (6.10.0.364) lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
[0d3df8f7-9a61-4c2e-aa0e-d7a5be4fd22f] remotipart (1.4.2) lib/remotipart/middleware.rb:32:in `call'
[0d3df8f7-9a61-4c2e-aa0e-d7a5be4fd22f] newrelic_rpm (6.10.0.364) lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
[0d3df8f7-9a61-4c2e-aa0e-d7a5be4fd22f] warden (1.2.8) lib/warden/manager.rb:36:in `block in call'
[0d3df8f7-9a61-4c2e-aa0e-d7a5be4fd22f] warden (1.2.8) lib/warden/manager.rb:34:in `catch'
[0d3df8f7-9a61-4c2e-aa0e-d7a5be4fd22f] warden (1.2.8) lib/warden/manager.rb:34:in `call'
[0d3df8f7-9a61-4c2e-aa0e-d7a5be4fd22f] newrelic_rpm (6.10.0.364) lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
[0d3df8f7-9a61-4c2e-aa0e-d7a5be4fd22f] rack (2.2.3) lib/rack/etag.rb:27:in `call'
[0d3df8f7-9a61-4c2e-aa0e-d7a5be4fd22f] newrelic_rpm (6.10.0.364) lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
[0d3df8f7-9a61-4c2e-aa0e-d7a5be4fd22f] rack (2.2.3) lib/rack/conditional_get.rb:40:in `call'
[0d3df8f7-9a61-4c2e-aa0e-d7a5be4fd22f] newrelic_rpm (6.10.0.364) lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
[0d3df8f7-9a61-4c2e-aa0e-d7a5be4fd22f] rack (2.2.3) lib/rack/head.rb:12:in `call'
[0d3df8f7-9a61-4c2e-aa0e-d7a5be4fd22f] newrelic_rpm (6.10.0.364) lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
[0d3df8f7-9a61-4c2e-aa0e-d7a5be4fd22f] rack (2.2.3) lib/rack/session/abstract/id.rb:266:in `context'
[0d3df8f7-9a61-4c2e-aa0e-d7a5be4fd22f] rack (2.2.3) lib/rack/session/abstract/id.rb:260:in `call'
[0d3df8f7-9a61-4c2e-aa0e-d7a5be4fd22f] newrelic_rpm (6.10.0.364) lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
[0d3df8f7-9a61-4c2e-aa0e-d7a5be4fd22f] actionpack (5.1.7) lib/action_dispatch/middleware/cookies.rb:613:in `call'
[0d3df8f7-9a61-4c2e-aa0e-d7a5be4fd22f] newrelic_rpm (6.10.0.364) lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
[0d3df8f7-9a61-4c2e-aa0e-d7a5be4fd22f] actionpack (5.1.7) lib/action_dispatch/middleware/callbacks.rb:26:in `block in call'
[0d3df8f7-9a61-4c2e-aa0e-d7a5be4fd22f] activesupport (5.1.7) lib/active_support/callbacks.rb:97:in `run_callbacks'
[0d3df8f7-9a61-4c2e-aa0e-d7a5be4fd22f] actionpack (5.1.7) lib/action_dispatch/middleware/callbacks.rb:24:in `call'
[0d3df8f7-9a61-4c2e-aa0e-d7a5be4fd22f] newrelic_rpm (6.10.0.364) lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
[0d3df8f7-9a61-4c2e-aa0e-d7a5be4fd22f] raygun4ruby (3.2.4) lib/raygun/middleware/rails_insert_affected_user.rb:11:in `call'
[0d3df8f7-9a61-4c2e-aa0e-d7a5be4fd22f] newrelic_rpm (6.10.0.364) lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
[0d3df8f7-9a61-4c2e-aa0e-d7a5be4fd22f] raygun4ruby (3.2.4) lib/raygun/middleware/breadcrumbs_store_initializer.rb:12:in `call'
[0d3df8f7-9a61-4c2e-aa0e-d7a5be4fd22f] newrelic_rpm (6.10.0.364) lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
[0d3df8f7-9a61-4c2e-aa0e-d7a5be4fd22f] raygun4ruby (3.2.4) lib/raygun/middleware/javascript_exception_tracking.rb:8:in `call'
[0d3df8f7-9a61-4c2e-aa0e-d7a5be4fd22f] newrelic_rpm (6.10.0.364) lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
[0d3df8f7-9a61-4c2e-aa0e-d7a5be4fd22f] actionpack (5.1.7) lib/action_dispatch/middleware/debug_exceptions.rb:59:in `call'
[0d3df8f7-9a61-4c2e-aa0e-d7a5be4fd22f] newrelic_rpm (6.10.0.364) lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
[0d3df8f7-9a61-4c2e-aa0e-d7a5be4fd22f] actionpack (5.1.7) lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'
[0d3df8f7-9a61-4c2e-aa0e-d7a5be4fd22f] newrelic_rpm (6.10.0.364) lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
[0d3df8f7-9a61-4c2e-aa0e-d7a5be4fd22f] railties (5.1.7) lib/rails/rack/logger.rb:36:in `call_app'
[0d3df8f7-9a61-4c2e-aa0e-d7a5be4fd22f] railties (5.1.7) lib/rails/rack/logger.rb:24:in `block in call'
[0d3df8f7-9a61-4c2e-aa0e-d7a5be4fd22f] activesupport (5.1.7) lib/active_support/tagged_logging.rb:69:in `block in tagged'
[0d3df8f7-9a61-4c2e-aa0e-d7a5be4fd22f] activesupport (5.1.7) lib/active_support/tagged_logging.rb:26:in `tagged'
[0d3df8f7-9a61-4c2e-aa0e-d7a5be4fd22f] activesupport (5.1.7) lib/active_support/tagged_logging.rb:69:in `tagged'
[0d3df8f7-9a61-4c2e-aa0e-d7a5be4fd22f] railties (5.1.7) lib/rails/rack/logger.rb:24:in `call'
[0d3df8f7-9a61-4c2e-aa0e-d7a5be4fd22f] newrelic_rpm (6.10.0.364) lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
[0d3df8f7-9a61-4c2e-aa0e-d7a5be4fd22f] actionpack (5.1.7) lib/action_dispatch/middleware/remote_ip.rb:79:in `call'
[0d3df8f7-9a61-4c2e-aa0e-d7a5be4fd22f] newrelic_rpm (6.10.0.364) lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
[0d3df8f7-9a61-4c2e-aa0e-d7a5be4fd22f] request_store (1.4.1) lib/request_store/middleware.rb:19:in `call'
[0d3df8f7-9a61-4c2e-aa0e-d7a5be4fd22f] newrelic_rpm (6.10.0.364) lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
[0d3df8f7-9a61-4c2e-aa0e-d7a5be4fd22f] actionpack (5.1.7) lib/action_dispatch/middleware/request_id.rb:25:in `call'
[0d3df8f7-9a61-4c2e-aa0e-d7a5be4fd22f] newrelic_rpm (6.10.0.364) lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
[0d3df8f7-9a61-4c2e-aa0e-d7a5be4fd22f] rack (2.2.3) lib/rack/method_override.rb:24:in `call'
[0d3df8f7-9a61-4c2e-aa0e-d7a5be4fd22f] newrelic_rpm (6.10.0.364) lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
[0d3df8f7-9a61-4c2e-aa0e-d7a5be4fd22f] rack (2.2.3) lib/rack/runtime.rb:22:in `call'
[0d3df8f7-9a61-4c2e-aa0e-d7a5be4fd22f] newrelic_rpm (6.10.0.364) lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
[0d3df8f7-9a61-4c2e-aa0e-d7a5be4fd22f] actionpack (5.1.7) lib/action_dispatch/middleware/executor.rb:12:in `call'
[0d3df8f7-9a61-4c2e-aa0e-d7a5be4fd22f] newrelic_rpm (6.10.0.364) lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
[0d3df8f7-9a61-4c2e-aa0e-d7a5be4fd22f] rack (2.2.3) lib/rack/sendfile.rb:110:in `call'
[0d3df8f7-9a61-4c2e-aa0e-d7a5be4fd22f] newrelic_rpm (6.10.0.364) lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
[0d3df8f7-9a61-4c2e-aa0e-d7a5be4fd22f] honeybadger (4.7.2) lib/honeybadger/rack/error_notifier.rb:33:in `block in call'
[0d3df8f7-9a61-4c2e-aa0e-d7a5be4fd22f] honeybadger (4.7.2) lib/honeybadger/agent.rb:403:in `with_rack_env'
[0d3df8f7-9a61-4c2e-aa0e-d7a5be4fd22f] honeybadger (4.7.2) lib/honeybadger/rack/error_notifier.rb:30:in `call'
[0d3df8f7-9a61-4c2e-aa0e-d7a5be4fd22f] newrelic_rpm (6.10.0.364) lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
[0d3df8f7-9a61-4c2e-aa0e-d7a5be4fd22f] honeybadger (4.7.2) lib/honeybadger/rack/user_feedback.rb:31:in `call'
[0d3df8f7-9a61-4c2e-aa0e-d7a5be4fd22f] newrelic_rpm (6.10.0.364) lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
[0d3df8f7-9a61-4c2e-aa0e-d7a5be4fd22f] honeybadger (4.7.2) lib/honeybadger/rack/user_informer.rb:21:in `call'
[0d3df8f7-9a61-4c2e-aa0e-d7a5be4fd22f] newrelic_rpm (6.10.0.364) lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
[0d3df8f7-9a61-4c2e-aa0e-d7a5be4fd22f] railties (5.1.7) lib/rails/engine.rb:522:in `call'
[0d3df8f7-9a61-4c2e-aa0e-d7a5be4fd22f] newrelic_rpm (6.10.0.364) lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
[0d3df8f7-9a61-4c2e-aa0e-d7a5be4fd22f] passenger (6.0.5) src/ruby_supportlib/phusion_passenger/rack/thread_handler_extension.rb:107:in `process_request'
[0d3df8f7-9a61-4c2e-aa0e-d7a5be4fd22f] passenger (6.0.5) src/ruby_supportlib/phusion_passenger/request_handler/thread_handler.rb:157:in `accept_and_process_next_request'
[0d3df8f7-9a61-4c2e-aa0e-d7a5be4fd22f] passenger (6.0.5) src/ruby_supportlib/phusion_passenger/request_handler/thread_handler.rb:110:in `main_loop'
[0d3df8f7-9a61-4c2e-aa0e-d7a5be4fd22f] passenger (6.0.5) src/ruby_supportlib/phusion_passenger/request_handler.rb:415:in `block (3 levels) in start_threads'
[0d3df8f7-9a61-4c2e-aa0e-d7a5be4fd22f] passenger (6.0.5) src/ruby_supportlib/phusion_passenger/utils.rb:113:in `block in create_thread_and_abort_on_exception'
-0.00s
```

**Comment by Deacon-McIntyre** [comment]
Hi @fatfrog, please try updating your raygun-apm-rails gem to version 1.0.58, we released a fix for this problem yesterday.

Let me know if that resolves this for you.

**Comment by fatfrog** [comment]
Thanks for the quick response, yes the updated gem worked.
