### ISSUE TITLE
Runtime exception on send raised in 1.3.3 - apparent conflict involving json_pure

### ISSUE THREAD

**Issue by fundead** [MindscapeHQ/raygun4ruby#37]
Issue discovered by a customer in production environment when this gem stopped reporting errors.
1. Typo in lib/raygun.rb line 53: `e.backrace.join` should be `e.backtrace.join`
2. This is preventing the actual reporting of the exception raised by the gem when attempting to send, of which the backtrace is this:

```
Problem reporting exception to Raygun: IOError: not opened for reading 
/Users/<user>/.rbenv/versions/1.9.3-p484/lib/ruby/gems/1.9.1/gems/activesupport-3.1.12/lib/active_support/json/encoding.rb:210:in `each'
 /Users/<user>/.rbenv/versions/1.9.3-p484/lib/ruby/gems/1.9.1/gems/activesupport-3.1.12/lib/active_support/json/encoding.rb:210:in `to_a'
 /Users/<user>/.rbenv/versions/1.9.3-p484/lib/ruby/gems/1.9.1/gems/activesupport-3.1.12/lib/active_support/json/encoding.rb:210:in `as_json'
 /Users/<user>/.rbenv/versions/1.9.3-p484/lib/ruby/gems/1.9.1/gems/activesupport-3.1.12/lib/active_support/json/encoding.rb:55:in `block in as_json'
 /Users/<user>/.rbenv/versions/1.9.3-p484/lib/ruby/gems/1.9.1/gems/activesupport-3.1.12/lib/active_support/json/encoding.rb:78:in `check_for_circular_references'
 /Users/<user>/.rbenv/versions/1.9.3-p484/lib/ruby/gems/1.9.1/gems/activesupport-3.1.12/lib/active_support/json/encoding.rb:54:in `as_json'
 /Users/<user>/.rbenv/versions/1.9.3-p484/lib/ruby/gems/1.9.1/gems/activesupport-3.1.12/lib/active_support/json/encoding.rb:245:in `block in as_json'
 /Users/<user>/.rbenv/versions/1.9.3-p484/lib/ruby/gems/1.9.1/gems/activesupport-3.1.12/lib/active_support/json/encoding.rb:245:in `each'
 /Users/<user>/.rbenv/versions/1.9.3-p484/lib/ruby/gems/1.9.1/gems/activesupport-3.1.12/lib/active_support/json/encoding.rb:245:in `map'
 /Users/<user>/.rbenv/versions/1.9.3-p484/lib/ruby/gems/1.9.1/gems/activesupport-3.1.12/lib/active_support/json/encoding.rb:245:in `as_json'
 /Users/<user>/.rbenv/versions/1.9.3-p484/lib/ruby/gems/1.9.1/gems/activesupport-3.1.12/lib/active_support/json/encoding.rb:47:in `block in encode'
 /Users/<user>/.rbenv/versions/1.9.3-p484/lib/ruby/gems/1.9.1/gems/activesupport-3.1.12/lib/active_support/json/encoding.rb:78:in `check_for_circular_references'
 /Users/<user>/.rbenv/versions/1.9.3-p484/lib/ruby/gems/1.9.1/gems/activesupport-3.1.12/lib/active_support/json/encoding.rb:46:in `encode'
 /Users/<user>/.rbenv/versions/1.9.3-p484/lib/ruby/gems/1.9.1/gems/activesupport-3.1.12/lib/active_support/json/encoding.rb:255:in `block in encode_json'
 /Users/<user>/.rbenv/versions/1.9.3-p484/lib/ruby/gems/1.9.1/gems/activesupport-3.1.12/lib/active_support/json/encoding.rb:255:in `each'
 /Users/<user>/.rbenv/versions/1.9.3-p484/lib/ruby/gems/1.9.1/gems/activesupport-3.1.12/lib/active_support/json/encoding.rb:255:in `map'
 /Users/<user>/.rbenv/versions/1.9.3-p484/lib/ruby/gems/1.9.1/gems/activesupport-3.1.12/lib/active_support/json/encoding.rb:255:in `encode_json'
 /Users/<user>/.rbenv/versions/1.9.3-p484/lib/ruby/gems/1.9.1/gems/activesupport-3.1.12/lib/active_support/json/encoding.rb:48:in `block in encode'
 /Users/<user>/.rbenv/versions/1.9.3-p484/lib/ruby/gems/1.9.1/gems/activesupport-3.1.12/lib/active_support/json/encoding.rb:78:in `check_for_circular_references'
 /Users/<user>/.rbenv/versions/1.9.3-p484/lib/ruby/gems/1.9.1/gems/activesupport-3.1.12/lib/active_support/json/encoding.rb:46:in `encode'
 /Users/<user>/.rbenv/versions/1.9.3-p484/lib/ruby/gems/1.9.1/gems/activesupport-3.1.12/lib/active_support/json/encoding.rb:31:in `encode'
 /Users/<user>/.rbenv/versions/1.9.3-p484/lib/ruby/gems/1.9.1/gems/activesupport-3.1.12/lib/active_support/core_ext/object/to_json.rb:20:in `to_json'
 /Users/<user>/.rbenv/versions/1.9.3-p484/lib/ruby/gems/1.9.1/gems/json_pure-1.8.1/lib/json/common.rb:223:in `generate'
 /Users/<user>/.rbenv/versions/1.9.3-p484/lib/ruby/gems/1.9.1/gems/json_pure-1.8.1/lib/json/common.rb:223:in `generate'
 /Users/<user>/.bundler/ruby/1.9.1/raygun4ruby-b19a9fd6f74c/lib/raygun/client.rb:130:in `create_entry'
 /Users/<user>/.bundler/ruby/1.9.1/raygun4ruby-b19a9fd6f74c/lib/raygun/client.rb:25:in `track_exception'
 /Users/<user>/.bundler/ruby/1.9.1/raygun4ruby-b19a9fd6f74c/lib/raygun.rb:49:in `track_exception'
 /Users/<user>/.bundler/ruby/1.9.1/raygun4ruby-b19a9fd6f74c/lib/raygun/middleware/rack_exception_interceptor.rb:12:in `rescue in call'
 /Users/<user>/.bundler/ruby/1.9.1/raygun4ruby-b19a9fd6f74c/lib/raygun/middleware/rack_exception_interceptor.rb:10:in `call'
 /Users/<user>/.rbenv/versions/1.9.3-p484/lib/ruby/gems/1.9.1/gems/newrelic_rpm-3.9.1.236/lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call'
 /Users/<user>/.rbenv/versions/1.9.3-p484/lib/ruby/gems/1.9.1/gems/actionpack-3.1.12/lib/action_dispatch/middleware/show_exceptions.rb:47:in `call'
 /Users/<user>/.rbenv/versions/1.9.3-p484/lib/ruby/gems/1.9.1/gems/newrelic_rpm-3.9.1.236/lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call'
 /Users/<user>/.rbenv/versions/1.9.3-p484/lib/ruby/gems/1.9.1/gems/railties-3.1.12/lib/rails/rack/logger.rb:13:in `call'
 /Users/<user>/.rbenv/versions/1.9.3-p484/lib/ruby/gems/1.9.1/gems/newrelic_rpm-3.9.1.236/lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call'
 /Users/<user>/.rbenv/versions/1.9.3-p484/lib/ruby/gems/1.9.1/gems/rack-1.3.10/lib/rack/methodoverride.rb:24:in `call'
 /Users/<user>/.rbenv/versions/1.9.3-p484/lib/ruby/gems/1.9.1/gems/newrelic_rpm-3.9.1.236/lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call'
 /Users/<user>/.rbenv/versions/1.9.3-p484/lib/ruby/gems/1.9.1/gems/rack-1.3.10/lib/rack/runtime.rb:17:in `call'
 /Users/<user>/.rbenv/versions/1.9.3-p484/lib/ruby/gems/1.9.1/gems/newrelic_rpm-3.9.1.236/lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call'
 /Users/<user>/.rbenv/versions/1.9.3-p484/lib/ruby/gems/1.9.1/gems/activesupport-3.1.12/lib/active_support/cache/strategy/local_cache.rb:72:in `call'
 /Users/<user>/.rbenv/versions/1.9.3-p484/lib/ruby/gems/1.9.1/gems/newrelic_rpm-3.9.1.236/lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call'
 /Users/<user>/.rbenv/versions/1.9.3-p484/lib/ruby/gems/1.9.1/gems/rack-1.3.10/lib/rack/lock.rb:15:in `call'
 /Users/<user>/.rbenv/versions/1.9.3-p484/lib/ruby/gems/1.9.1/gems/newrelic_rpm-3.9.1.236/lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call'
 /Users/<user>/.rbenv/versions/1.9.3-p484/lib/ruby/gems/1.9.1/gems/actionpack-3.1.12/lib/action_dispatch/middleware/static.rb:61:in `call'
 /Users/<user>/.rbenv/versions/1.9.3-p484/lib/ruby/gems/1.9.1/gems/newrelic_rpm-3.9.1.236/lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call'
 /Users/<user>/.rbenv/versions/1.9.3-p484/lib/ruby/gems/1.9.1/gems/railties-3.1.12/lib/rails/engine.rb:456:in `call'
 /Users/<user>/.rbenv/versions/1.9.3-p484/lib/ruby/gems/1.9.1/gems/railties-3.1.12/lib/rails/application.rb:143:in `call'
 /Users/<user>/.rbenv/versions/1.9.3-p484/lib/ruby/gems/1.9.1/gems/railties-3.1.12/lib/rails/railtie/configurable.rb:30:in `method_missing'
 /Users/<user>/.rbenv/versions/1.9.3-p484/lib/ruby/gems/1.9.1/gems/newrelic_rpm-3.9.1.236/lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call'
 /Users/<user>/.rbenv/versions/1.9.3-p484/lib/ruby/gems/1.9.1/gems/rack-1.3.10/lib/rack/content_length.rb:14:in `call'
 /Users/<user>/.rbenv/versions/1.9.3-p484/lib/ruby/gems/1.9.1/gems/railties-3.1.12/lib/rails/rack/log_tailer.rb:14:in `call'
 /Users/<user>/.rbenv/versions/1.9.3-p484/lib/ruby/gems/1.9.1/gems/rack-1.3.10/lib/rack/handler/webrick.rb:59:in `service'
 /Users/<user>/.rbenv/versions/1.9.3-p484/lib/ruby/1.9.1/webrick/httpserver.rb:138:in `service'
 /Users/<user>/.rbenv/versions/1.9.3-p484/lib/ruby/1.9.1/webrick/httpserver.rb:94:in `run'
 /Users/<user>/.rbenv/versions/1.9.3-p484/lib/ruby/1.9.1/webrick/server.rb:191:in `block in start_thread'

```

Quick triage indicates this could be the culprit - http://stackoverflow.com/questions/683989/how-do-you-deal-with-the-conflict-between-activesupportjson-and-the-json-gem (awaiting customer's Rails version to confirm)

**Comment by UberMouse** [comment]
Appears to be fixed by #38 so I'm closing
