### ISSUE TITLE
raygun getting errors looking for a Gemfile...?

### ISSUE THREAD

**Issue by angelacode** [MindscapeHQ/raygun4ruby#54]
I am getting the followng stacktrace when running my ruby program on iron.io....there isn't a persistent Gemfile because it creates the build from the Gemfile when I create the worker....so there is no Gemfile to find.  Do we really need to have a Gemfile available for raygun to work?

```
   /mnt/task/__gems__/gems/bundler-1.7.4/lib/bundler/shared_helpers.rb:24:in `default_gemfile': Could not locate Gemfile (Bundler::GemfileNotFound)
from /mnt/task/__gems__/gems/bundler-1.7.4/lib/bundler.rb:249:in `default_gemfile'
from /mnt/task/__gems__/gems/bundler-1.7.4/lib/bundler.rb:193:in `root'
from /mnt/task/__gems__/gems/bundler-1.7.4/lib/bundler.rb:100:in `bundle_path'
from /mnt/task/__gems__/gems/bundler-1.7.4/lib/bundler.rb:401:in `configure_gem_home_and_path'
from /mnt/task/__gems__/gems/bundler-1.7.4/lib/bundler.rb:91:in `configure'
from /mnt/task/__gems__/gems/bundler-1.7.4/lib/bundler.rb:152:in `definition'
from /mnt/task/__gems__/gems/bundler-1.7.4/lib/bundler.rb:117:in `setup'
from /mnt/task/__gems__/gems/raygun4ruby-1.1.4/lib/raygun.rb:2:in `<top (required)>'
from /usr/local/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
from /usr/local/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
from /mnt/task/__gems__/gems/raygun4ruby-1.1.4/lib/raygun4ruby.rb:1:in `<top (required)>'
```

**Comment by UberMouse** [comment]
Seems like it may have been fixed by #57 so I'm closing this
